# application: el-boli
# version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: res/favicon.ico
  upload: favicon\.ico
  
- url: /templates
  static_dir: templates
  application_readable: true

- url: /res
  static_dir: res
  
- url: /error
  script: handlers.error.app
  
- url: /info
  script: handlers.info.app
  
- url: /manage_stories
  script: handlers.manage_stories.app
  login: required
  
- url: /stories/add
  script: handlers.stories.add.app
  login: required
  
- url: /stories/modify
  script: handlers.stories.modify.app
  login: required
  
- url: /stories/delete
  script: handlers.stories.delete.app
  login: required

- url: /stories/export
  script: handlers.stories.export.app
  login: required

- url: /manage_chapters
  script: handlers.manage_chapters.app
  login: required

- url: /chapters/add
  script: handlers.chapters.add.app
  login: required

- url: /chapters/modify
  script: handlers.chapters.modify.app
  login: required

- url: /chapters/delete
  script: handlers.chapters.delete.app
  login: required

- url: /manage_characters
  script: handlers.manage_characters.app
  login: required

- url: /characters/add
  script: handlers.characters.add.app
  login: required

- url: /characters/modify
  script: handlers.characters.modify.app
  login: required

- url: /characters/delete
  script: handlers.characters.delete.app
  login: required

- url: /manage_sections
  script: handlers.manage_sections.app
  login: required

- url: /sections/add
  script: handlers.sections.add.app
  login: required

- url: /sections/modify
  script: handlers.sections.modify.app
  login: required

- url: /sections/delete
  script: handlers.sections.delete.app
  login: required

- url: /
  script: handlers.welcome.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
